### PR TITLE
cabal: fix dependency issue on network module

### PR DESCRIPTION
**Pull request by shivaken**

### CODE REVIEW

**Comment by shivaken** [comment]
On network-2.8.0.1, inet_addr is already deprecated like below, though. It actually helps us to build the service.
We need to find a time to fix the service to use `getAddrInfo` insead of `inet_addr`
```
src/Server.hs:60:11: warning: [-Wdeprecations]
    In the use of `inet_addr' (imported from Network.Socket):
    Deprecated: "Use "getAddrInfo" instead"
```

**Comment by ip1981** [comment]
Hi Kenichi :)

This might help: https://github.com/ip1981/sproxy2/commit/5af03230208f355c53c3b8f763d9533f9e859411

**Comment by shivaken** [comment]
Hi @ip1981 , nice. that must be better. 
Do you have sproxy-web modernized as well..?

**Comment by shivaken** [comment]
I found https://github.com/ip1981/sproxy-web

**Pull request merged**
